### ISSUE TITLE
[REQUEST] EmberZNet 6.8.0 (6.8 / 6.8.x / 6.8.x.x) NCP application firmware for IKEA TRADFRI ICC-A-1

### ISSUE THREAD

**Issue by Hedda** [MattWestb/IKEA-TRADFRI-ICC-A-1-Module#4]
@MattWestb OK to request an EmberZNet 6.8 NCP application firmware for IKEA TRADFRI ICC-A-1 as an optional download?

Related to https://github.com/arendst/Tasmota/issues/9316 

For using Tasmota zbbridge firmware on ESP8266 connected to IKEA TRÅDFRI ICC-A-1 module with same pins as Sonoff ZBBridge.

Silicon Labs EmberZNet SDK version 6.8.0 (6.8.0.2) was released this summer so it is new but not quite cutting-edge any more.

Please note that release notes say that EmberZNet PRO stack version 6.8.x requires latest Simplicity Studio 5 (SSv5) which is new.

Might be nice for developers and users to have the option to upgrade to the latest and greatest firmware available from SiLabs ;)

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.8.0.2.pdf

https://www.silabs.com/documents/public/quick-start-guides/qsg106-efr32-zigbee-pro.pdf

Major new Zigbee feature in EmberZNet 6.8 and later is support for concurrent multiple PANs (multi-PAN) on one coordinator:

https://www.silabs.com/documents/public/application-notes/an724-multi-network.pdf

There is also support for "Dynamic Multiprotocol Development with Bluetooth and Zigbee" which might not be as interesting.

https://www.silabs.com/documents/public/application-notes/an1133-dynamic-multiprotocol-bluetooth-zigbee.pdf

Keywords: IKEA Trådfri ICCA1 ZB Bridge Ember ZNet 6.8 Zigbee Stack EFR32 EFR32MG EFR32MG2 EFR32MG21 EZSP FW images.

**Comment by MattWestb** [comment]
@Hedda Im interested in the bug fixes that is in the newer releases but for the moment not the new futures that is not bringing any new useful for the end user (Multi zigbee networks is not supported by any HA programs that we are using to day).
Then Billy only having 256Kb flash so its not getting Zigbee R23 (if not stripping the firmware) is the plan waiting and requesting one "golden" (last R22 with all bug fixes) release from the firmware maker.
Also its good that SSv5 is setting down so bugs being fixed in it that can making bad things in the firmware and the firmware makers getting used with it.

**Comment by MattWestb** [comment]
Was reading little bit more and multi network and multi pan is not supported on devices with 256Kb flash and billy cant using its external flash for saving tokens that the ZB3 is needed for storing TC-lik keys and counters.
So in the end its only bug fixes that is interesting for the platform.
